name: bapenda_mdm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.5.0
  pocketbase: ^0.23.0
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  get: ^4.7.2
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
